// seeds/cities/hurghada.js

const cityData = {
  name: "Hurghada",
  nameAr: "الغردقة",
  slug: "hurghada",
  description:
    "Hurghada is Egypt's premier Red Sea resort city, stretching along a dazzling coastline of crystal-clear turquoise waters, vibrant coral reefs, and golden sandy beaches. Once a quiet fishing village, it has grown into one of the most popular holiday destinations in the Middle East and Africa, drawing millions of visitors each year with its world-class diving, water sports, desert adventures, and year-round sunshine. Whether you're gliding over coral gardens on a snorkeling trip, racing across desert dunes on a quad bike, or sailing to a private island paradise, Hurghada offers an endless variety of experiences for every type of traveler.",
  descriptionAr:
    "الغردقة هي مدينة المنتجعات الأولى على البحر الأحمر في مصر، تمتد على طول ساحل ساحر من المياه الفيروزية الصافية والشعاب المرجانية النابضة بالحياة والشواطئ الرملية الذهبية. كانت في السابق قرية صيد هادئة، وقد نمت لتصبح واحدة من أكثر الوجهات السياحية شعبية في الشرق الأوسط وأفريقيا، تستقطب ملايين الزوار سنوياً بغوصها العالمي المستوى والرياضات المائية ومغامرات الصحراء وأشعة الشمس على مدار العام.",
  country: "Egypt",
  image: "hurghada.jpg",
};

const toursData = [
  {
    title: "Guided Tour of Hurghada",
    titleAr: "جولة مصحوبة بمرشد في الغردقة",
    slug: "guided-tour-hurghada",
    description:
      "Discover the cultural and historical soul of Hurghada beyond its beaches on this engaging guided city tour. Your expert guide will take you through the most significant landmarks of the city, starting with the magnificent Grand Mosque, one of the most striking religious buildings on the Egyptian Red Sea coast, with its soaring minarets and beautifully decorated interior. The tour also visits the Coptic Church of Hurghada, offering a fascinating glimpse into one of the oldest Christian communities in the world, before exploring the lively local souk and the colorful fishermen's neighborhood.",
    descriptionAr:
      "اكتشف الروح الثقافية والتاريخية للغردقة ما وراء شواطئها في هذه الجولة المدينية المصحوبة بمرشد. سيأخذك مرشدك الخبير عبر أبرز معالم المدينة، بدءاً بالمسجد الكبير الرائع، أحد أبرز المباني الدينية على ساحل البحر الأحمر المصري، بمئذنته الشاهقة وتزيينه الداخلي الجميل. تزور الجولة أيضاً الكنيسة القبطية في الغردقة وتستكشف السوق المحلي الحيوي وحي الصيادين الملون.",
    category: "Guided tours and free tours",
    price: {
      original: 39.00,
      discounted: 31.20,
      currency: "USD",
    },
    duration: "4 hours",
    language: ["English"],
    rating: {
      score: 8.4,
      reviews: 65,
    },
    travellers: 600,
    freeCancellation: true,
    highlights: [
      "Visit the spectacular Grand Mosque of Hurghada",
      "Explore the historic Coptic Church",
      "Wander through the local souk and fishermen's area",
      "Learn about Hurghada's transformation from fishing village to resort city",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Guide", "Hotel pickup and drop-off", "Transport"],
    excludes: ["Entrance fees", "Meals", "Tips"],
  },
  {
    title: "Quad Bike & Dune Buggy Safari",
    titleAr: "سفاري الدراجات الرباعية وعربة الدونباجي",
    slug: "quad-bike-dune-buggy-safari-hurghada",
    description:
      "Tear across the magnificent Egyptian desert on this thrilling quad bike and dune buggy safari from Hurghada. Head out into the vast, sun-scorched landscape beyond the city and race across golden dunes, weaving between rocky outcrops and open desert plains. This action-packed adventure is perfect for those who want a taste of the raw, wild side of Egypt away from the beach. Suitable for both beginners and experienced riders, the tour includes all safety equipment and a briefing before you set off.",
    descriptionAr:
      "اندفع عبر الصحراء المصرية الرائعة في هذه السفاري المثيرة بالدراجات الرباعية وعربات الدونباجي من الغردقة. توجه إلى المشهد الواسع المحترق بالشمس خارج المدينة وتسابق عبر الكثبان الذهبية متلوياً بين التكوينات الصخرية والسهول الصحراوية المفتوحة. هذه المغامرة المليئة بالإثارة مثالية لمن يريد تذوق الجانب البري الوحشي من مصر بعيداً عن الشاطئ.",
    category: "Adventure and nature",
    price: {
      original: 39.39,
      discounted: null,
      currency: "USD",
    },
    duration: "4 hours",
    language: ["English"],
    rating: {
      score: 7.5,
      reviews: 22,
    },
    travellers: 219,
    freeCancellation: true,
    highlights: [
      "Exciting quad bike and dune buggy ride in the desert",
      "Race across golden sand dunes outside Hurghada",
      "Suitable for beginners and experienced riders",
      "All safety equipment provided",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Quad bike or dune buggy", "Safety equipment", "Hotel pickup and drop-off", "Guide"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Luxor Tour & Valley of the Kings and Queens from Hurghada",
    titleAr: "جولة الأقصر ووادي الملوك والملكات من الغردقة",
    slug: "luxor-valley-kings-queens-tour-hurghada",
    description:
      "Make the most of your time in Hurghada with this extraordinary day trip to the ancient wonders of Luxor. Depart early from Hurghada and travel across the Egyptian landscape to the world's greatest open-air museum, where you'll visit the colossal Karnak Temple, the legendary Valley of the Kings with its royal tombs, the Valley of the Queens, the Mortuary Temple of Hatshepsut, and the Colossi of Memnon. With an expert guide bringing history to life throughout the day, this is one of the most rewarding excursions available from the Red Sea coast.",
    descriptionAr:
      "استثمر وقتك في الغردقة مع هذه الرحلة اليومية الاستثنائية إلى عجائب الأقصر القديمة. غادر مبكراً من الغردقة وسافر عبر المشهد المصري إلى أعظم متحف مفتوح في العالم، حيث ستزور معبد الكرنك الهائل ووادي الملوك الأسطوري بمقابره الملكية ووادي الملكات ومعبد حتشبسوت الجنائزي وتمثالي ممنون.",
    category: "Day trip",
    price: {
      original: 260.03,
      discounted: 208.03,
      currency: "USD",
    },
    duration: "18 hours",
    language: ["English"],
    rating: {
      score: 7.2,
      reviews: 31,
    },
    travellers: 533,
    freeCancellation: true,
    highlights: [
      "Full-day trip from Hurghada to Luxor",
      "Visit Karnak Temple and Luxor's West Bank",
      "Explore the Valley of the Kings and Queens",
      "See the Mortuary Temple of Hatshepsut",
      "Admire the Colossi of Memnon",
      "Hotel pickup at dawn included",
    ],
    includes: ["Guide", "Hotel pickup and drop-off", "Entrance fees", "Lunch", "Transport"],
    excludes: ["Tutankhamun tomb (extra fee)", "Tips", "Personal expenses"],
  },
  {
    title: "Red Sea Beginners Scuba Diving",
    titleAr: "الغوص للمبتدئين في البحر الأحمر",
    slug: "red-sea-beginners-scuba-diving-hurghada",
    description:
      "Plunge into the breathtaking underwater world of the Red Sea on this beginner-friendly scuba diving experience. No prior experience is needed — your certified instructor will give you a thorough briefing and all the basic training you need before you enter the water. Once beneath the surface, you'll glide over spectacular coral reefs teeming with colorful fish, sea turtles, and exotic marine life that make the Red Sea one of the top diving destinations in the world. A truly life-changing underwater adventure.",
    descriptionAr:
      "انغمس في العالم المائي الرائع للبحر الأحمر في هذه التجربة الصديقة للمبتدئين في الغوص. لا تحتاج إلى خبرة سابقة — سيعطيك مدربك المعتمد إحاطة شاملة وكل التدريب الأساسي الذي تحتاجه قبل دخول الماء. بمجرد أن تكون تحت السطح ستنزلق فوق شعاب مرجانية رائعة مليئة بالأسماك الملونة والسلاحف البحرية والحياة البحرية الغريبة.",
    category: "Adventure and nature",
    price: {
      original: 53.19,
      discounted: 42.55,
      currency: "USD",
    },
    duration: "7 hours",
    language: ["English"],
    rating: {
      score: 8.4,
      reviews: 79,
    },
    travellers: 831,
    freeCancellation: true,
    highlights: [
      "Beginner scuba diving in the Red Sea coral reefs",
      "No prior experience required",
      "Certified instructor throughout the dive",
      "Two underwater dive points",
      "All diving equipment provided",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Diving equipment", "Certified instructor", "Hotel pickup and drop-off", "Refreshments"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Orange Bay Snorkel Tour",
    titleAr: "جولة الغطس في خليج أورانج",
    slug: "orange-bay-snorkel-tour-hurghada",
    description:
      "Escape to one of the Red Sea's most beautiful natural paradises on this full-day boat trip to Orange Bay. Sail south from Hurghada to reach this stunning stretch of pristine coastline, where turquoise waters meet untouched white sand beaches and thriving coral reefs. Strap on your snorkel and fins and dive into a magical underwater world filled with colorful fish and vibrant marine life, then relax on the beach, soak up the Egyptian sun, and enjoy the peaceful beauty of this unforgettable Red Sea destination.",
    descriptionAr:
      "اهرب إلى واحدة من أجمل جنات الطبيعة في البحر الأحمر في هذه الرحلة البحرية اليومية إلى خليج أورانج. أبحر جنوباً من الغردقة للوصول إلى هذا الامتداد الرائع من الساحل البكر، حيث تلتقي المياه الفيروزية بالشواطئ الرملية البيضاء النقية والشعاب المرجانية المزدهرة. ارتدِ أدوات الغطس وانغمس في عالم مائي سحري.",
    category: "Day trip",
    price: {
      original: 22.00,
      discounted: null,
      currency: "USD",
    },
    duration: "8 hours",
    language: ["English"],
    rating: {
      score: 9.1,
      reviews: 45,
    },
    travellers: 1132,
    freeCancellation: true,
    highlights: [
      "Boat trip to the stunning Orange Bay",
      "Snorkeling in pristine coral reefs",
      "Relax on a beautiful white sand beach",
      "Crystal-clear turquoise waters",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Transfers in Hurghada",
    titleAr: "خدمة التوصيل في الغردقة",
    slug: "transfers-hurghada",
    description:
      "Start and end your Hurghada experience with total peace of mind using our reliable private transfer service. Whether you need a smooth airport pickup, a hotel transfer, or a ride to any address in the city, a professional chauffeur will be waiting for you with a clean, air-conditioned vehicle. Fast, safe, and door-to-door — the most hassle-free way to get around Hurghada at any time of day or night.",
    descriptionAr:
      "ابدأ تجربتك في الغردقة وأنهِها براحة بال تامة باستخدام خدمة النقل الخاصة الموثوقة لدينا. سواء كنت تحتاج إلى استقبال سلس من المطار أو نقل فندقي أو توصيلة إلى أي عنوان في المدينة، سيكون سائق محترف في انتظارك بسيارة نظيفة ومكيفة.",
    category: "Transfers",
    price: {
      original: 9.45,
      discounted: null,
      currency: "USD",
    },
    duration: "Varies",
    language: ["English"],
    rating: {
      score: 8.3,
      reviews: 76,
    },
    travellers: 2608,
    freeCancellation: true,
    highlights: [
      "Private door-to-door transfer service",
      "Professional and punctual chauffeur",
      "Air-conditioned vehicle",
      "Airport, hotel, and custom pickups",
      "Available 24/7",
    ],
    includes: ["Private vehicle", "Professional driver"],
    excludes: ["Tips", "Entrance fees to any attractions"],
  },
  {
    title: "Desert Safari & Bedouin Dinner",
    titleAr: "سفاري الصحراء وعشاء البدو",
    slug: "desert-safari-bedouin-dinner-hurghada",
    description:
      "Venture deep into the rugged Egyptian desert on this thrilling off-road safari before settling in for a magical Bedouin evening under the stars. Climb aboard a powerful 4x4 vehicle and race across the golden dunes and rocky desert terrain surrounding Hurghada, stopping at a traditional Bedouin village to learn about the ancient nomadic way of life in the Egyptian desert. As the sun sets, enjoy a camel ride and then gather around a fire for a delicious traditional Bedouin dinner with local music and hospitality.",
    descriptionAr:
      "توجه عميقاً في الصحراء المصرية الوعرة في هذه السفاري المثيرة على الطرق الوعرة قبل الاستقرار لسهرة بدوية سحرية تحت النجوم. اصعد إلى سيارة دفع رباعي قوية وتسابق عبر الكثبان الذهبية والتضاريس الصخرية المحيطة بالغردقة، مع توقف في قرية بدوية تقليدية للتعرف على أسلوب الحياة البدوية القديم.",
    category: "Day trip",
    price: {
      original: 53.19,
      discounted: 42.55,
      currency: "USD",
    },
    duration: "6-7 hours",
    language: ["English"],
    rating: {
      score: 6.7,
      reviews: 50,
    },
    travellers: 688,
    freeCancellation: true,
    highlights: [
      "Off-road 4x4 desert safari through the dunes",
      "Visit a traditional Bedouin village",
      "Camel ride through the desert",
      "Traditional Bedouin dinner under the stars",
      "Live music and local hospitality",
      "Hotel pickup and drop-off included",
    ],
    includes: ["4x4 vehicle", "Guide", "Camel ride", "Bedouin dinner", "Hotel pickup and drop-off"],
    excludes: ["Tips", "Personal expenses", "Alcoholic drinks"],
  },
  {
    title: "Orange Bay Speedboat Trip",
    titleAr: "رحلة قارب السرعة إلى خليج أورانج",
    slug: "orange-bay-speedboat-trip-hurghada",
    description:
      "Feel the rush of the Red Sea wind on your face as you speed across the water on this exciting speedboat trip to Orange Bay. Race south along the coastline before arriving at one of the most beautiful beach destinations in Egypt, where pristine white sands and crystal-clear waters await. Spend time swimming, sunbathing, and exploring the colorful coral reefs by snorkel before the boat whisks you back to Hurghada. A perfect combination of adrenaline and relaxation in one of the Red Sea's most scenic spots.",
    descriptionAr:
      "اشعر بهبوب رياح البحر الأحمر على وجهك وأنت تتسابق عبر الماء في هذه الرحلة المثيرة بقارب السرعة إلى خليج أورانج. اندفع جنوباً على طول الساحل قبل الوصول إلى واحدة من أجمل وجهات الشواطئ في مصر، حيث تنتظرك الرمال البيضاء البكر والمياه الصافية.",
    category: "Day trip",
    price: {
      original: 88.65,
      discounted: 75.35,
      currency: "USD",
    },
    duration: "5 hours",
    language: ["English"],
    rating: {
      score: 9.0,
      reviews: 2,
    },
    travellers: 54,
    freeCancellation: true,
    highlights: [
      "Thrilling speedboat ride to Orange Bay",
      "Swim and snorkel in crystal-clear Red Sea waters",
      "Relax on a beautiful pristine beach",
      "Explore colorful coral reefs",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Speedboat trip", "Snorkeling equipment", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Hurghada Grand Aquarium Trip",
    titleAr: "زيارة أكواريوم الغردقة الكبير",
    slug: "hurghada-grand-aquarium-trip",
    description:
      "Dive into the wonders of the Red Sea without getting wet at the Hurghada Grand Aquarium, also known as the Red Sea in Glass. This world-class aquarium is home to an extraordinary collection of marine life native to the Red Sea, including sea turtles, sharks, manta rays, and hundreds of species of colorful reef fish. Walk through immersive underwater tunnels, watch feeding sessions, and discover the rich biodiversity of Egypt's most treasured sea in a fascinating and educational experience suitable for all ages.",
    descriptionAr:
      "انغمس في عجائب البحر الأحمر دون أن تبتل في أكواريوم الغردقة الكبير، المعروف أيضاً بـ 'البحر الأحمر في الزجاج'. يضم هذا الأكواريوم العالمي المستوى مجموعة استثنائية من الحياة البحرية الأصيلة في البحر الأحمر، بما في ذلك السلاحف البحرية وأسماك القرش والراي والمئات من أنواع أسماك الشعاب الملونة.",
    category: "Entrance tickets",
    price: {
      original: 47.28,
      discounted: null,
      currency: "USD",
    },
    duration: "9 hours",
    language: ["English"],
    rating: {
      score: 0,
      reviews: 0,
    },
    travellers: 43,
    freeCancellation: true,
    highlights: [
      "Explore the Hurghada Grand Aquarium (Red Sea in Glass)",
      "See sharks, sea turtles, and manta rays",
      "Walk through immersive underwater tunnels",
      "Hundreds of Red Sea marine species on display",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Aquarium entrance", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Swim with Dolphins in Hurghada",
    titleAr: "السباحة مع الدلافين في الغردقة",
    slug: "swim-with-dolphins-hurghada",
    description:
      "Create memories that will last a lifetime on this magical boat trip where you'll swim alongside friendly dolphins in the warm waters of the Red Sea. Head out from Hurghada to Dolphin House, a famous snorkeling site known for its resident pod of spinner dolphins that love to interact with swimmers. Slip into the water and experience the extraordinary thrill of these incredible animals gliding around you in their natural habitat. The adventure continues with a banana boat ride and more time to snorkel over the vibrant coral reef.",
    descriptionAr:
      "اصنع ذكريات ستدوم مدى الحياة في هذه الرحلة البحرية السحرية حيث ستسبح جانباً لجانب مع الدلافين الودودة في المياه الدافئة للبحر الأحمر. اتجه من الغردقة إلى بيت الدولفين، وهو موقع غطس شهير معروف بقطيعه المقيم من دلافين سبينر التي تحب التفاعل مع السباحين.",
    category: "Adventure and nature",
    price: {
      original: 53.19,
      discounted: 42.55,
      currency: "USD",
    },
    duration: "8 hours",
    language: ["English"],
    rating: {
      score: 7.6,
      reviews: 27,
    },
    travellers: 454,
    freeCancellation: true,
    highlights: [
      "Swim with wild spinner dolphins at Dolphin House",
      "Snorkel over vibrant coral reefs",
      "Banana boat ride included",
      "Experience dolphins in their natural habitat",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Banana boat ride", "Hotel pickup and drop-off", "Light refreshments"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Day Trip to the Pyramids of Giza + Egyptian Museum",
    titleAr: "رحلة يوم إلى أهرامات الجيزة والمتحف المصري",
    slug: "day-trip-pyramids-giza-egyptian-museum-hurghada",
    description:
      "No visit to Egypt is complete without seeing the Pyramids of Giza, and this exciting day trip by plane from Hurghada makes it possible in just one day. Fly to Cairo and spend the day exploring two of Egypt's greatest treasures: the iconic Pyramids of Giza and the Great Sphinx, followed by a visit to the Grand Egyptian Museum, home to the world's largest collection of ancient Egyptian artifacts including the treasures of Tutankhamun. A full-day journey through the very best of ancient and modern Egypt.",
    descriptionAr:
      "لا تكتمل زيارة مصر دون رؤية أهرامات الجيزة، وهذه الرحلة اليومية المثيرة بالطائرة من الغردقة تجعل ذلك ممكناً في يوم واحد. اطر إلى القاهرة وأمضِ اليوم في استكشاف اثنين من أعظم كنوز مصر: أهرامات الجيزة الأيقونية وأبو الهول الكبير، يليها زيارة المتحف المصري الكبير.",
    category: "Day trip",
    price: {
      original: 410.15,
      discounted: null,
      currency: "USD",
    },
    duration: "15 hours",
    language: ["English"],
    rating: {
      score: 8.0,
      reviews: 5,
    },
    travellers: 32,
    freeCancellation: true,
    highlights: [
      "Round-trip flight from Hurghada to Cairo",
      "Visit the iconic Pyramids of Giza and the Great Sphinx",
      "Explore the Grand Egyptian Museum",
      "See Tutankhamun's golden treasures",
      "Expert guide throughout the day",
    ],
    includes: ["Round-trip flight", "Guide", "Entrance fees", "Lunch", "Hotel pickup and drop-off"],
    excludes: ["Entry inside the Great Pyramid (extra fee)", "Tips", "Personal expenses"],
  },
  {
    title: "Fly Board in Hurghada",
    titleAr: "الفلايبورد في الغردقة",
    slug: "flyboard-hurghada",
    description:
      "Defy gravity and soar above the Red Sea on an electrifying flyboarding session in Hurghada. Powered by water jets attached to your feet, you'll rise up from the surface of the sea and hover in the air like a superhero, with breathtaking views of the Red Sea and the Hurghada coastline stretching out around you. An experienced instructor will guide you throughout the session, making this adrenaline-pumping water sport accessible even for first-timers looking for the ultimate Red Sea thrill.",
    descriptionAr:
      "تحدَّ الجاذبية وحلّق فوق البحر الأحمر في جلسة فلايبورد مثيرة في الغردقة. مدفوعاً بنفاثات مياه مرتبطة بقدميك ستنطلق إلى الأعلى من سطح البحر وتحلق في الهواء كبطل خارق مع مناظر خلابة للبحر الأحمر وساحل الغردقة تمتد حولك.",
    category: "Adventure and nature",
    price: {
      original: 106.38,
      discounted: 85.10,
      currency: "USD",
    },
    duration: "30 minutes",
    language: ["English"],
    rating: {
      score: 10.0,
      reviews: 2,
    },
    travellers: 8,
    freeCancellation: true,
    highlights: [
      "Thrilling flyboarding experience over the Red Sea",
      "Rise several meters above the water surface",
      "Experienced instructor guides you throughout",
      "Suitable for first-timers",
      "Stunning aerial views of the Red Sea coastline",
    ],
    includes: ["Flyboarding session", "Safety equipment", "Instructor"],
    excludes: ["Hotel pickup", "Tips", "Personal expenses"],
  },
  {
    title: "Civitatis eSIM Card Egypt",
    titleAr: "شريحة eSIM لمصر من Civitatis",
    slug: "civitatis-esim-card-egypt-hurghada",
    description:
      "Stay seamlessly connected throughout your Egyptian holiday with this convenient travel eSIM card. Whether you're sharing stunning Red Sea sunset photos, navigating between Hurghada's resorts, or looking up information about the ancient sites you're visiting, this eSIM gives you reliable mobile data coverage across Egypt without the need to swap physical SIM cards. Simply activate digitally on your smartphone before arrival and you're good to go.",
    descriptionAr:
      "ابقَ متصلاً بسلاسة طوال عطلتك المصرية مع بطاقة eSIM السياحية المريحة هذه. سواء كنت تشارك صور غروب البحر الأحمر الرائعة أو تتنقل بين منتجعات الغردقة أو تبحث عن معلومات حول المواقع الأثرية التي تزورها، تمنحك هذه البطاقة تغطية بيانات جوال موثوقة في جميع أنحاء مصر.",
    category: "Additional services",
    price: {
      original: 5.50,
      discounted: null,
      currency: "USD",
    },
    duration: "7-30 days",
    language: ["English"],
    rating: {
      score: 7.7,
      reviews: 89,
    },
    travellers: 1856,
    freeCancellation: false,
    highlights: [
      "Mobile data coverage across Egypt",
      "No physical SIM swap needed",
      "Easy digital activation before arrival",
      "Available in 7, 15, and 30-day plans",
      "Works throughout Hurghada and all Egyptian destinations",
    ],
    includes: ["eSIM data plan for selected duration"],
    excludes: ["Voice calls", "SMS"],
  },
  {
    title: "Horseback Riding in Hurghada",
    titleAr: "ركوب الخيل في الغردقة",
    slug: "horseback-riding-hurghada",
    description:
      "Experience the timeless romance of riding through the Egyptian desert and along the shores of the Red Sea on horseback. This guided ride takes you through stunning desert landscapes and down to the beach, where you'll canter along the water's edge with the Red Sea breeze in your hair and the wide blue sea stretching before you. Suitable for both beginners and experienced riders, this is one of Hurghada's most unique and memorable outdoor activities.",
    descriptionAr:
      "اختبر رومانسية الزمن في ركوب الخيل عبر الصحراء المصرية وعلى طول شواطئ البحر الأحمر. تأخذك هذه الجولة المصحوبة بمرشد عبر مناظر صحراوية خلابة وصولاً إلى الشاطئ، حيث ستركض على طول حافة المياه مع نسيم البحر الأحمر في شعرك والبحر الأزرق الواسع ممتداً أمامك.",
    category: "Adventure and nature",
    price: {
      original: 42.55,
      discounted: null,
      currency: "USD",
    },
    duration: "4 hours",
    language: ["English"],
    rating: {
      score: 6.5,
      reviews: 4,
    },
    travellers: 30,
    freeCancellation: true,
    highlights: [
      "Horseback ride through desert and along the beach",
      "Stunning Red Sea coastal scenery",
      "Suitable for beginners and experienced riders",
      "Professional horse handlers throughout",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Horse", "Guide", "Safety equipment", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Glass Bottomed Boat Tour",
    titleAr: "جولة القارب ذو القاع الزجاجي",
    slug: "glass-bottom-boat-tour-hurghada",
    description:
      "Peer into the stunning underwater world of the Red Sea without getting wet on this fascinating glass-bottomed boat tour. Glide over the shimmering waters of the Red Sea coast as the transparent hull reveals the breathtaking marine world beneath — colorful coral gardens, schools of tropical fish, and the occasional sea turtle or reef shark passing below. A wonderful experience for the whole family and a perfect way to appreciate the incredible biodiversity of the Red Sea's famous reefs.",
    descriptionAr:
      "تطلع إلى العالم المائي الرائع للبحر الأحمر دون أن تبتل في هذه الجولة الرائعة بالقارب ذي القاع الزجاجي. انزلق فوق المياه المتلألئة لساحل البحر الأحمر بينما يكشف الهيكل الشفاف عن العالم البحري المذهل تحته — حدائق مرجانية ملونة وأسراب أسماك استوائية وسلحفاة بحرية أو سمكة قرش شعاب تمر من الأسفل.",
    category: "Boat tour",
    price: {
      original: 31.91,
      discounted: 25.53,
      currency: "USD",
    },
    duration: "3 hours",
    language: ["English"],
    rating: {
      score: 7.6,
      reviews: 9,
    },
    travellers: 96,
    freeCancellation: true,
    highlights: [
      "View Red Sea marine life through the glass bottom",
      "See colorful coral reefs without diving",
      "Spot tropical fish, sea turtles, and reef sharks",
      "Perfect for families and non-swimmers",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat tour", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Sharm El-Naga Snorkel Trip",
    titleAr: "رحلة الغطس في شرم الناقة",
    slug: "sharm-el-naga-snorkel-trip-hurghada",
    description:
      "Head south to one of the most beautiful and unspoiled snorkeling destinations on the Red Sea coast — Sharm El-Naga. This protected natural bay is renowned for its healthy coral reefs, crystal-clear visibility, and rich marine life that includes turtles, rays, and dozens of species of colorful reef fish. Spend the day exploring the underwater world at this pristine location, relaxing on the beach, and enjoying the wild, uncrowded beauty of the Red Sea away from the busy resort areas.",
    descriptionAr:
      "توجه جنوباً إلى واحدة من أجمل وأنقى وجهات الغطس على ساحل البحر الأحمر — شرم الناقة. تشتهر هذه الخليج الطبيعية المحمية بشعابها المرجانية الصحية ووضوح مياهها البلوري وحياتها البحرية الغنية التي تشمل السلاحف والراي وعشرات أنواع أسماك الشعاب الملونة.",
    category: "Day trip",
    price: {
      original: 70.92,
      discounted: null,
      currency: "USD",
    },
    duration: "8 hours",
    language: ["English"],
    rating: {
      score: 8.0,
      reviews: 2,
    },
    travellers: 24,
    freeCancellation: true,
    highlights: [
      "Snorkeling at the pristine Sharm El-Naga bay",
      "Healthy coral reefs with exceptional visibility",
      "Spot sea turtles, rays, and tropical fish",
      "Relax on an unspoiled Red Sea beach",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Transport", "Snorkeling equipment", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Desert Quad Tour + Bedouin Dinner",
    titleAr: "جولة الكواد في الصحراء مع عشاء بدوي",
    slug: "desert-quad-tour-bedouin-dinner-hurghada",
    description:
      "Get your adrenaline pumping on this classic desert quad bike adventure followed by an authentic Bedouin evening experience. Ride out into the vast desert surrounding Hurghada on a powerful quad bike, navigating sand dunes, rocky trails, and open desert plains as the landscape changes dramatically around you. After the ride, visit a traditional Bedouin village for a camel ride and then settle in for a delicious Bedouin dinner under the stars, complete with traditional music, shisha, and warm desert hospitality.",
    descriptionAr:
      "اشحن طاقتك في هذه المغامرة الكلاسيكية بالدراجة الرباعية في الصحراء يليها سهرة بدوية أصيلة. اركب إلى الصحراء الواسعة المحيطة بالغردقة على دراجة رباعية قوية، متنقلاً بين الكثبان الرملية والمسالك الصخرية والسهول الصحراوية المفتوحة.",
    category: "Adventure and nature",
    price: {
      original: 53.19,
      discounted: 42.55,
      currency: "USD",
    },
    duration: "5 hours",
    language: ["English"],
    rating: {
      score: 6.2,
      reviews: 13,
    },
    travellers: 243,
    freeCancellation: true,
    highlights: [
      "Quad bike ride through the Egyptian desert",
      "Visit a traditional Bedouin village",
      "Camel ride experience",
      "Authentic Bedouin dinner under the stars",
      "Traditional music and shisha",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Quad bike", "Safety equipment", "Camel ride", "Bedouin dinner", "Hotel pickup and drop-off"],
    excludes: ["Tips", "Personal expenses", "Alcoholic drinks"],
  },
  {
    title: "Turkish Bath in Hurghada",
    titleAr: "الحمام التركي في الغردقة",
    slug: "turkish-bath-hurghada",
    description:
      "Treat yourself to a deeply relaxing and rejuvenating traditional Turkish bath experience in Hurghada. Unwind in the warm steam room, enjoy a full body scrub with a traditional kessa mitt to remove dead skin and leave you feeling refreshed from head to toe, followed by a relaxing foam massage and a soothing full-body oil massage. It's the perfect way to recover after days of sightseeing, diving, and desert adventures — a true oasis of calm in the heart of Egypt's busiest resort city.",
    descriptionAr:
      "دلّل نفسك بتجربة الحمام التركي التقليدي العميق الاسترخاء والمنعش في الغردقة. استرخِ في غرفة البخار الدافئة واستمتع بتقشير الجسم الكامل بقفاز الكيس التقليدي لإزالة الخلايا الميتة وتركك منتعشاً من الرأس إلى أخمص القدمين، يليه تدليك رغوي مريح وتدليك كامل للجسم بالزيت.",
    category: "Entrance tickets",
    price: {
      original: 53.19,
      discounted: 42.55,
      currency: "USD",
    },
    duration: "3 hours",
    language: ["English"],
    rating: {
      score: 8.5,
      reviews: 4,
    },
    travellers: 41,
    freeCancellation: true,
    highlights: [
      "Traditional Turkish bath (hammam) experience",
      "Full body scrub with kessa mitt",
      "Relaxing foam massage",
      "Full-body oil massage",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Turkish bath session", "Body scrub", "Foam massage", "Oil massage", "Hotel pickup and drop-off"],
    excludes: ["Tips", "Personal expenses"],
  },
  {
    title: "Great Pyramid of Giza + Grand Egyptian Museum Bus Day Trip",
    titleAr: "رحلة يومية بالأتوبيس إلى هرم الجيزة والمتحف المصري الكبير",
    slug: "pyramid-giza-grand-egyptian-museum-bus-hurghada",
    description:
      "Discover the greatest wonders of ancient and modern Egypt on this full-day bus trip from Hurghada to Cairo. Travel in comfort along the road to Cairo and spend the day at two of Egypt's most iconic destinations — the Great Pyramid of Giza, the last surviving Wonder of the Ancient World, and the Grand Egyptian Museum, the largest archaeological museum on Earth. With an expert guide, you'll gain deep insight into over 5,000 years of Egyptian civilization in a single unforgettable day.",
    descriptionAr:
      "اكتشف أعظم عجائب مصر القديمة والحديثة في هذه الرحلة اليومية بالأتوبيس من الغردقة إلى القاهرة. سافر بكل راحة على طريق القاهرة وأمضِ اليوم في وجهتين من أكثر وجهات مصر أيقونية — هرم الجيزة الأكبر، آخر عجائب الدنيا السبع القديمة التي لا تزال قائمة، والمتحف المصري الكبير، أكبر متحف أثري على وجه الأرض.",
    category: "Day trip",
    price: {
      original: 180.00,
      discounted: null,
      currency: "USD",
    },
    duration: "18-19 hours",
    language: ["English"],
    rating: {
      score: 8.0,
      reviews: 1,
    },
    travellers: 13,
    freeCancellation: true,
    highlights: [
      "Full-day bus trip from Hurghada to Cairo",
      "Visit the Great Pyramid of Giza and the Sphinx",
      "Explore the Grand Egyptian Museum",
      "See Tutankhamun's golden treasures",
      "Expert guide throughout the day",
    ],
    includes: ["Bus transport", "Guide", "Entrance fees", "Lunch", "Hotel pickup and drop-off"],
    excludes: ["Entry inside the Great Pyramid (extra fee)", "Tips", "Personal expenses"],
  },
  {
    title: "Giftun Island Snorkelling Tour",
    titleAr: "جولة الغطس في جزيرة جفتون",
    slug: "giftun-island-snorkelling-hurghada",
    description:
      "Sail to the spectacular Giftun Island, one of the most beautiful and biodiverse marine areas in the entire Red Sea, on this full-day snorkeling adventure from Hurghada. Giftun Island is part of a protected national park and is home to some of the healthiest coral reefs in Egypt, teeming with sea turtles, colourful reef fish, and other extraordinary marine creatures. Spend the day snorkeling over these pristine reefs, relaxing on the island's stunning beaches, and enjoying the untouched natural beauty of this Red Sea gem.",
    descriptionAr:
      "أبحر إلى جزيرة جفتون الرائعة، إحدى أجمل المناطق البحرية وأكثرها تنوعاً بيولوجياً في البحر الأحمر بأكمله، في هذه المغامرة اليومية للغطس من الغردقة. جزيرة جفتون جزء من حديقة وطنية محمية وتضم بعضاً من أصح الشعاب المرجانية في مصر.",
    category: "Day trip",
    price: {
      original: 53.19,
      discounted: 42.55,
      currency: "USD",
    },
    duration: "8 hours",
    language: ["English"],
    rating: {
      score: 10.0,
      reviews: 45,
    },
    travellers: 750,
    freeCancellation: true,
    highlights: [
      "Boat trip to Giftun Island National Park",
      "Snorkel over pristine protected coral reefs",
      "Spot sea turtles and tropical marine life",
      "Relax on Giftun Island's beautiful beaches",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Hotel pickup and drop-off", "Light refreshments"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Hurghada Submarine Tour",
    titleAr: "جولة الغواصة في الغردقة",
    slug: "hurghada-submarine-tour",
    description:
      "Descend beneath the surface of the Red Sea without getting wet on this unique and thrilling submarine tour in Hurghada. Board the famous Sindbad submarine and sink below the waves to explore the incredible underwater world of the Red Sea coast. Through large portholes, you'll be treated to close-up views of brilliant coral formations, lionfish, butterflyfish, scarlet frogfish, and many other extraordinary species that call these reefs home. A recorded English commentary enhances the experience, making this a fascinating educational adventure for the whole family.",
    descriptionAr:
      "انزل تحت سطح البحر الأحمر دون أن تبتل في هذه الجولة الفريدة والمثيرة بالغواصة في الغردقة. اصعد على متن غواصة سندباد الشهيرة واغطس تحت الأمواج لاستكشاف العالم المائي الرائع لساحل البحر الأحمر. من خلال فتحات كبيرة ستحظى بمناظر مقربة لتكوينات مرجانية رائعة وأسماك الأسد والفراشة وأسماك الضفدع القرمزية والعديد من الأنواع الاستثنائية الأخرى.",
    category: "Boat tour",
    price: {
      original: 53.19,
      discounted: 42.55,
      currency: "USD",
    },
    duration: "2 hours",
    language: ["English"],
    rating: {
      score: 8.2,
      reviews: 35,
    },
    travellers: 420,
    freeCancellation: true,
    highlights: [
      "Underwater submarine ride along Hurghada's coast",
      "View Red Sea marine life through large portholes",
      "See coral reefs, lionfish, and exotic species",
      "English audio commentary throughout",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Submarine ride", "English audio commentary", "Hotel pickup and drop-off", "Soft drink"],
    excludes: ["Tips", "Personal expenses"],
  },
  {
    title: "El Gouna Boat Trip & Water Activities",
    titleAr: "رحلة قارب وأنشطة مائية في الجونة",
    slug: "el-gouna-boat-trip-water-activities-hurghada",
    description:
      "Discover El Gouna, Egypt's most glamorous resort town often called the Venice of Egypt, on this unforgettable boat trip and water activities day from Hurghada. Cruise across the Red Sea to reach El Gouna's stunning lagoons and drop anchor for a full day of fun — snorkel over vibrant coral reefs, try your luck at banana boating, go fishing, or hop on a semi-submarine for a peek beneath the waves. A buffet lunch is served onboard, and if you're lucky you might spot wild dolphins dancing alongside the boat.",
    descriptionAr:
      "اكتشف الجونة، أكثر مدن المنتجعات المصرية أناقة والمعروفة بـ 'البندقية المصرية'، في هذه الرحلة البحرية اليومية الذكرى مع أنشطة مائية من الغردقة. أبحر عبر البحر الأحمر للوصول إلى بحيرات الجونة الرائعة وأرسِ المرساة ليوم كامل من المتعة.",
    category: "Boat tour",
    price: {
      original: 76.15,
      discounted: null,
      currency: "USD",
    },
    duration: "8 hours 30 minutes",
    language: ["English"],
    rating: {
      score: 0,
      reviews: 0,
    },
    travellers: 9,
    freeCancellation: true,
    highlights: [
      "Boat trip to the glamorous El Gouna resort",
      "Snorkeling, banana boating, and fishing",
      "Semi-submarine ride option",
      "Chance to spot wild dolphins en route",
      "Buffet lunch onboard included",
    ],
    includes: ["Boat trip", "Water activities", "Buffet lunch", "Hotel pickup and drop-off"],
    excludes: ["Tips", "Personal expenses"],
  },
  {
    title: "Utopia Island Excursion",
    titleAr: "رحلة جزيرة يوتوبيا",
    slug: "utopia-island-excursion-hurghada",
    description:
      "Spend a dreamy day on Utopia Island, a private paradise island in the Red Sea offering some of the finest snorkeling, swimming, and beach relaxation in the Hurghada region. The island's crystal-clear waters and thriving coral reefs are home to a dazzling variety of tropical fish, rays, and sea turtles, making it one of the most rewarding snorkeling spots on the Egyptian coast. Enjoy a full day of water sports, sunbathing, and the kind of pure, unspoiled Red Sea beauty that Hurghada is famous for.",
    descriptionAr:
      "أمضِ يوماً حالماً في جزيرة يوتوبيا، جزيرة خاصة في البحر الأحمر تقدم بعضاً من أفضل تجارب الغطس والسباحة والاسترخاء على الشاطئ في منطقة الغردقة. مياه الجزيرة الصافية وشعابها المرجانية المزدهرة موطن لمجموعة رائعة من الأسماك الاستوائية والراي والسلاحف البحرية.",
    category: "Day trip",
    price: {
      original: 64.43,
      discounted: null,
      currency: "USD",
    },
    duration: "8 hours 30 minutes",
    language: ["English"],
    rating: {
      score: 8.0,
      reviews: 3,
    },
    travellers: 159,
    freeCancellation: true,
    highlights: [
      "Full day on the private Utopia Island",
      "Snorkeling in pristine coral reefs",
      "Spot sea turtles, rays, and tropical fish",
      "Water sports and beach relaxation",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Island access", "Snorkeling equipment", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "Red Sea 8-Day All-Inclusive Tour from Hurghada",
    titleAr: "باقة البحر الأحمر 8 أيام شاملة من الغردقة",
    slug: "red-sea-8-day-all-inclusive-tour-hurghada",
    description:
      "Immerse yourself fully in the magic of Hurghada and the Red Sea on this comprehensive 8-day all-inclusive tour package. From exploring the desert on a 4x4 safari and quad bikes to snorkeling over world-class coral reefs, swimming with dolphins, and discovering the city's cultural highlights — this package covers the very best of what Hurghada has to offer. All accommodation, meals, activities, and transfers are included, so all you have to do is show up and enjoy every moment.",
    descriptionAr:
      "انغمس كلياً في سحر الغردقة والبحر الأحمر في هذه الباقة السياحية الشاملة التي تمتد 8 أيام. من استكشاف الصحراء على سيارة 4x4 ودراجات رباعية إلى الغطس على شعاب مرجانية عالمية المستوى والسباحة مع الدلافين واكتشاف معالم المدينة الثقافية — تغطي هذه الباقة أفضل ما تقدمه الغردقة.",
    category: "Tour packages",
    price: {
      original: 850.00,
      discounted: null,
      currency: "USD",
    },
    duration: "8 days",
    language: ["English"],
    rating: {
      score: 8.0,
      reviews: 12,
    },
    travellers: 95,
    freeCancellation: false,
    highlights: [
      "8 days all-inclusive in Hurghada",
      "Desert safari and quad bike adventure",
      "Snorkeling and diving in the Red Sea",
      "Swim with dolphins excursion",
      "Guided city tour of Hurghada",
      "All accommodation and meals included",
    ],
    includes: [
      "7 nights hotel accommodation",
      "All meals (breakfast, lunch, dinner)",
      "All activities as per itinerary",
      "All transport and transfers",
      "English-speaking guide",
    ],
    excludes: ["International flights", "Travel insurance", "Tips", "Personal expenses", "Alcoholic drinks"],
  },
  {
    title: "Orange Bay Pirate Cruise",
    titleAr: "رحلة القراصنة إلى خليج أورانج",
    slug: "orange-bay-pirate-cruise-hurghada",
    description:
      "Ahoy! Set sail on a swashbuckling pirate cruise from Hurghada to the beautiful Orange Bay for a day of high-seas fun, snorkeling, and Red Sea adventures. Dress up, play the part, and enjoy a lively atmosphere aboard the pirate-themed cruise ship as you sail to one of the most scenic and pristine bays on the Egyptian coast. Once anchored at Orange Bay, jump into the sparkling turquoise water to snorkel over the coral reefs before relaxing on the stunning beach. A fantastic experience for families, groups, and anyone looking for a fun day on the water.",
    descriptionAr:
      "أهلاً! أبحر في رحلة قراصنة مغامرة من الغردقة إلى خليج أورانج الجميل ليوم من المتعة وركوب البحار العالية والغطس ومغامرات البحر الأحمر. البِس الزي وأدِّ دورك واستمتع بالأجواء الحيوية على متن سفينة الرحلة ذات الطابع القرصاني وأنت تبحر إلى واحدة من أجمل الخلجان وأنقاها على الساحل المصري.",
    category: "Boat tour",
    price: {
      original: 35.00,
      discounted: null,
      currency: "USD",
    },
    duration: "8 hours",
    language: ["English"],
    rating: {
      score: 8.5,
      reviews: 18,
    },
    travellers: 280,
    freeCancellation: true,
    highlights: [
      "Pirate-themed cruise to Orange Bay",
      "Snorkeling over pristine coral reefs",
      "Relax on a beautiful Red Sea beach",
      "Fun atmosphere with entertainment onboard",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Hotel pickup and drop-off", "Light refreshments"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
  {
    title: "El Gouna City Tour",
    titleAr: "جولة مدينة الجونة",
    slug: "el-gouna-city-tour-hurghada",
    description:
      "Discover El Gouna, one of Egypt's most unique and beautifully designed resort cities, on this dedicated guided city tour from Hurghada. Built across a series of islands and lagoons on the Red Sea coast, El Gouna has its own airport, marina, golf course, and a charming old town. Enjoy a traditional felucca ride through the city's scenic waterways, tour the vibrant downtown and harbor area, and take in the stunning views of the lagoons and Red Sea that make El Gouna one of the most photogenic spots in Egypt.",
    descriptionAr:
      "اكتشف الجونة، إحدى أكثر مدن المنتجعات المصرية فرادة وجمالاً في التصميم، في هذه الجولة المدينية المصحوبة بمرشد من الغردقة. مبنية عبر سلسلة من الجزر والبحيرات على ساحل البحر الأحمر، تمتلك الجونة مطارها الخاص ومرساها وملعب غولف وبلدة قديمة ساحرة. استمتع برحلة فلوكة تقليدية عبر الممرات المائية المنظرية للمدينة.",
    category: "Guided tours and free tours",
    price: {
      original: 55.00,
      discounted: null,
      currency: "USD",
    },
    duration: "6 hours",
    language: ["English"],
    rating: {
      score: 8.0,
      reviews: 14,
    },
    travellers: 175,
    freeCancellation: true,
    highlights: [
      "Guided tour of the unique El Gouna resort city",
      "Traditional felucca ride through the lagoons",
      "Visit the harbor and downtown area",
      "Stunning views of the Red Sea lagoons",
      "Hotel pickup and drop-off from Hurghada included",
    ],
    includes: ["Guide", "Felucca ride", "Transport from Hurghada", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
  },
];

export { cityData, toursData };