// seeds/cities/marsa-alam.js

const cityData = {
  name: "Marsa Alam",
  slug: "marsa-alam",
  description:
    "Marsa Alam is one of Egypt's best-kept secrets — a pristine and largely unspoiled stretch of the Red Sea coast that offers some of the finest diving, snorkeling, and wildlife encounters in the world. Located about 200 kilometers south of Hurghada, this laid-back coastal town feels a world away from the crowded resorts of the north, attracting travelers who seek raw natural beauty, extraordinary marine life, and genuine tranquility rather than nightlife and crowded beach bars. While Hurghada and Sharm el Sheikh built themselves into mass-tourism hubs decades ago, Marsa Alam developed more slowly and more quietly, and that slower pace shows in everything from the smaller hotel footprints to the noticeably healthier coral reefs just offshore. The waters here are home to spinner dolphins, dugongs, sea turtles, hammerhead sharks, and spectacular coral reefs at legendary sites like Elphinstone Reef and Sataya Dolphin House, names that experienced Red Sea divers speak of with a kind of reverence usually reserved for far more remote destinations. Inland, the vast Eastern Desert stretches to the horizon, dotted with ancient Pharaonic gold mines that fed the wealth of dynasties thousands of years ago, scattered Bedouin villages whose way of life has changed remarkably little, and dramatic desert scenery that turns the whole region into a genuine choice between sea and sand rather than a token excursion squeezed in between beach days.",
  country: "Egypt",
  image: "marsa-alam.jpg",
};

// ─────────────────────────────────────────────
//  CITY-WIDE ITINERARY  (5 days recommended)
// ─────────────────────────────────────────────
const cityItinerary = {
  title: "5-Day Marsa Alam Explorer",
  totalDays: 5,
  recommendedFor: ["Divers", "Snorkelers", "Wildlife lovers", "Desert adventurers"],
  narrative:
    "Five days is the sweet spot for Marsa Alam — long enough to experience both the extraordinary Red Sea underwater world and the vast silence of the Eastern Desert, yet short enough to leave you hungry to return rather than worn out by the end of it. Days one and two ease you into the water with accessible snorkeling bays, the kind of gentle, shallow introductions that let first-timers and seasoned snorkelers alike find their rhythm before the trip's bigger moments arrive. Day three is the crown jewel: a full day at Sataya Dolphin House, an experience that regularly tops the list of things travelers remember most from an entire Egyptian holiday. Day four swaps fins for quad-bike tyres in the desert, trading the blue of the sea for the gold and rust of the Eastern Desert and a Bedouin village that still runs on its own ancient rhythm. Day five closes with either a deeper dive or a leisurely morning on the beach before departure, a gentle wind-down after four days of genuinely big experiences.",
  days: [
    {
      dayNumber: 1,
      title: "Arrival & Turtle Bay Welcome",
      theme: "Easy snorkeling — settle in gently",
      schedule: [
        { time: "09:00", activity: "Hotel pickup and transfer to Marsa Mubarak (Turtle Bay)" },
        { time: "09:30", activity: "First snorkeling session — explore the seagrass beds and spot wild sea turtles feeding" },
        { time: "11:00", activity: "Break on the boat — drinks and fresh fruit" },
        { time: "11:30", activity: "Second snorkeling session — reef fish and coral formations" },
        { time: "13:00", activity: "Buffet lunch on board with Egyptian dishes" },
        { time: "14:30", activity: "Return to shore and hotel drop-off" },
        { time: "16:00", activity: "Free time — rest, beach walk, or hotel pool" },
        { time: "19:30", activity: "Dinner at a local seafood restaurant in Marsa Alam town" },
      ],
      recommendedTour: "snorkeling-marsa-mubarak-marsa-alam",
      tips: "Bring reef-safe sunscreen and a rash guard — the midday sun on the water is intense.",
    },
    {
      dayNumber: 2,
      title: "Two Bays, One Morning",
      theme: "Sharm El Luli + Wadi El Qulaan national park",
      schedule: [
        { time: "07:30", activity: "Hotel pickup — early start to beat the midday heat" },
        { time: "08:00", activity: "Boat trip to Sharm El Luli — arrive at the turquoise natural bay" },
        { time: "08:30", activity: "Snorkeling session 1 at Sharm El Luli — vibrant coral reef and reef fish" },
        { time: "10:00", activity: "Short beach break on Sharm El Luli's powder-white sand" },
        { time: "10:30", activity: "Move by boat to Wadi El Qulaan National Park waters" },
        { time: "11:00", activity: "Snorkeling session 2 — sea turtles, pristine ecosystems inside the protected park" },
        { time: "12:30", activity: "Return to shore — hotel drop-off" },
        { time: "14:00", activity: "Lunch and afternoon rest" },
        { time: "17:00", activity: "Optional: Semi-submarine tour for a no-wet alternative view of the reef" },
        { time: "20:00", activity: "Dinner at hotel or beachside restaurant" },
      ],
      recommendedTour: "snorkel-sharm-luli-wadi-qulaan-marsa-alam",
      tips: "Wadi El Qulaan is a protected national park — no touching corals or feeding fish.",
    },
    {
      dayNumber: 3,
      title: "Dolphin House — The Crown Jewel",
      theme: "Full day at Sataya Reef with wild spinner dolphins",
      schedule: [
        { time: "06:30", activity: "Hotel pickup — very early departure to reach Sataya before other boats" },
        { time: "07:00", activity: "Depart marina heading south towards Sataya Reef" },
        { time: "09:30", activity: "Arrive at Sataya Dolphin House — briefing on dolphin interaction etiquette" },
        { time: "10:00", activity: "First snorkeling session — enter the water with the resident pod of spinner dolphins" },
        { time: "11:30", activity: "Back on boat — rest, refreshments, guide shares facts about Red Sea dolphins" },
        { time: "12:00", activity: "Explore the reef caves and underwater tunnels around Sataya — second snorkel" },
        { time: "13:30", activity: "Buffet lunch on board — fresh fruit, Egyptian mezze, grilled fish" },
        { time: "14:30", activity: "Relaxed afternoon — sunbathing on deck or optional third snorkel at the reef wall" },
        { time: "16:00", activity: "Begin return journey north to Marsa Alam" },
        { time: "18:30", activity: "Arrive marina — hotel drop-off" },
        { time: "20:30", activity: "Celebratory dinner — you've just swum with wild dolphins" },
      ],
      recommendedTour: "sataya-reef-boat-trip-snorkeling-dolphins-marsa-alam",
      tips: "Do not chase, touch, or surround the dolphins — let them approach you. Spinner dolphins rest in the morning so be quiet and patient in the water.",
    },
    {
      dayNumber: 4,
      title: "Desert Day — Dunes, Bedouin & Stars",
      theme: "Eastern Desert quad, camel ride, Bedouin village & dinner under the stars",
      schedule: [
        { time: "09:00", activity: "Hotel pickup — head inland towards the Eastern Desert" },
        { time: "09:30", activity: "Safety briefing and quad bike familiarization" },
        { time: "10:00", activity: "1-hour quad bike ride — 25-30 km through golden dunes and rocky desert plains" },
        { time: "11:00", activity: "Arrive at traditional Bedouin village — sweet Bedouin tea and cultural exchange" },
        { time: "11:45", activity: "15-minute camel ride through the dunes" },
        { time: "12:30", activity: "Return to hotel — rest and beach time during peak afternoon heat" },
        { time: "15:00", activity: "Optional: Red Sea Semi-Submarine Tour if not done on Day 2 evening" },
        { time: "17:30", activity: "Second hotel pickup — head back to desert for sunset experience" },
        { time: "18:00", activity: "Watch the sun set over the Eastern Desert dunes" },
        { time: "18:30", activity: "Camel ride through the cooling desert at dusk" },
        { time: "19:30", activity: "Gather around the campfire — traditional Bedouin live music and dance show" },
        { time: "20:30", activity: "Bedouin dinner under a vast star-filled sky" },
        { time: "22:00", activity: "Return to hotel" },
      ],
      recommendedTour: "desert-quad-camel-ride-dinner-show-marsa-alam",
      tips: "Wear long sleeves and closed shoes for the quad — desert dust is fine and the sun is strong even in the morning.",
    },
    {
      dayNumber: 5,
      title: "Final Dive or Gentle Farewell",
      theme: "Beginner scuba dive OR leisurely morning beach day before departure",
      schedule: [
        { time: "08:00", activity: "Hotel pickup — head to the dive centre for morning briefing (divers) OR free beach morning (non-divers)" },
        { time: "08:30", activity: "[Divers] Dry land safety and technique briefing with certified instructor" },
        { time: "09:30", activity: "[Divers] First scuba dive at Marsa Alam reef — pristine corals and tropical fish" },
        { time: "11:00", activity: "[Divers] Surface interval — rest and refreshments" },
        { time: "11:30", activity: "[Divers] Second scuba dive at a second reef location" },
        { time: "13:00", activity: "Return to hotel — final lunch" },
        { time: "14:30", activity: "Pack, shower, last beach walk" },
        { time: "16:00", activity: "Departure transfer to Marsa Alam Airport or onward destination" },
      ],
      recommendedTour: "red-sea-beginners-scuba-diving-marsa-alam",
      tips: "If flying out, remember the 18-hour no-fly rule after scuba diving. Plan your last dive accordingly, or opt for snorkeling instead.",
    },
  ],
};

// ─────────────────────────────────────────────
//  TOURS DATA  (each with tourSchedule field)
// ─────────────────────────────────────────────
const toursData = [
  {
    title: "Snorkel Sharm El Luli & Wadi El Qulaan",
    slug: "snorkel-sharm-luli-wadi-qulaan-marsa-alam",
    description:
      "Spend a magical morning snorkeling at two of the most beautiful and biodiverse marine sites on the Red Sea coast near Marsa Alam, each one offering a distinctly different flavor of underwater Egypt within a single short boat trip. Sharm El Luli is a breathtaking natural bay with crystal-clear turquoise waters, a powder-white sandy beach, and thriving coral reefs teeming with colorful marine life, the kind of postcard scene that often surprises visitors who didn't expect this stretch of coast to look quite so vivid in person. Wadi El Qulaan is part of a protected national park with pristine underwater ecosystems, sea turtles, and spectacular reef fish, its protected status keeping it noticeably less disturbed than reefs closer to busier resort areas. Together, they offer a truly unforgettable Red Sea snorkeling experience in some of Egypt's most unspoiled natural environments.",
    category: "Adventure and nature",
    price: {
      original: 35.00,
      discounted: null,
      currency: "USD",
    },
    duration: "4 hours",
    language: ["English"],
    rating: {
      score: 8.2,
      reviews: 24,
    },
    travellers: 312,
    freeCancellation: true,
    highlights: [
      "Snorkeling at the stunning Sharm El Luli bay",
      "Explore Wadi El Qulaan National Park waters",
      "See sea turtles, colorful fish, and coral reefs",
      "Two of Marsa Alam's most pristine snorkeling spots",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Guide", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "4 hours",
      startTime: "07:30",
      endTime: "11:30",
      narrative:
        "An early-morning two-bay snorkeling adventure that starts at the iconic Sharm El Luli natural bay, then moves to the protected waters of Wadi El Qulaan National Park. Early departure is essential to catch the calmer sea conditions and softer morning light that make the corals glow, before the wind picks up and the midday glare flattens the underwater colors.",
      steps: [
        { time: "07:30", durationMinutes: 15, step: "Hotel pickup and transfer to Marsa Alam marina" },
        { time: "07:45", durationMinutes: 15, step: "Board the boat — equipment distribution and guide safety briefing" },
        { time: "08:00", durationMinutes: 30, step: "Boat trip to Sharm El Luli bay" },
        { time: "08:30", durationMinutes: 60, step: "First snorkeling session at Sharm El Luli — vibrant coral reef, reef fish, and the beautiful powder-white beach" },
        { time: "09:30", durationMinutes: 30, step: "Short beach break on Sharm El Luli — rest on the sand, drinks served" },
        { time: "10:00", durationMinutes: 15, step: "Boat moves to Wadi El Qulaan National Park marine area" },
        { time: "10:15", durationMinutes: 60, step: "Second snorkeling session — sea turtles, pristine coral ecosystems inside the protected national park" },
        { time: "11:15", durationMinutes: 15, step: "Return boat trip to marina and hotel drop-off" },
      ],
    },
  },
  {
    title: "Snorkeling in Marsa Mubarak",
    slug: "snorkeling-marsa-mubarak-marsa-alam",
    description:
      "Discover the extraordinary marine beauty of Marsa Mubarak — one of the most beautiful and protected bays on Egypt's Red Sea coastline — on this full-day snorkeling boat trip from Marsa Alam. Known locally as Turtle Bay, Marsa Mubarak is a legendary spot for encounters with wild sea turtles that feed on the seagrass beds just below the surface, often close enough to observe their unhurried grazing for minutes at a time, as well as a rich variety of reef fish and coral formations spread across the bay's shallow, sheltered waters. You'll have two dedicated snorkeling sessions to explore this remarkable underwater world, with a delicious buffet lunch served on board between dives, leaving plenty of time to simply float and watch rather than rushing from one sighting to the next.",
    category: "Boat tour",
    price: {
      original: 42.00,
      discounted: null,
      currency: "USD",
    },
    duration: "8 hours",
    language: ["English"],
    rating: {
      score: 8.0,
      reviews: 31,
    },
    travellers: 428,
    freeCancellation: true,
    highlights: [
      "Two snorkeling sessions in Marsa Mubarak (Turtle Bay)",
      "Swim alongside wild sea turtles",
      "Explore pristine protected coral reefs",
      "Buffet lunch with Egyptian dishes served on board",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Buffet lunch", "Hotel pickup and drop-off"],
    excludes: ["Wetsuit rental", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "8 hours",
      startTime: "08:00",
      endTime: "16:00",
      narrative:
        "A full day centered on Marsa Mubarak — Turtle Bay — one of Egypt's most protected and biodiverse marine bays. Two snorkeling sessions bookend a generous on-board buffet lunch, giving you maximum time in the water with the resident sea turtle population rather than the rushed single dip that shorter tours offer elsewhere.",
      steps: [
        { time: "08:00", durationMinutes: 15, step: "Hotel pickup and transfer to marina" },
        { time: "08:15", durationMinutes: 15, step: "Board boat — equipment fitting and safety briefing" },
        { time: "08:30", durationMinutes: 30, step: "Boat trip to Marsa Mubarak (Turtle Bay)" },
        { time: "09:00", durationMinutes: 90, step: "First snorkeling session — sea turtle encounters at the seagrass feeding grounds, reef fish and coral formations" },
        { time: "10:30", durationMinutes: 30, step: "Back on board — rest, drinks and guide commentary on marine life" },
        { time: "11:00", durationMinutes: 90, step: "Second snorkeling session — deeper reef exploration, coral gardens and tropical fish schools" },
        { time: "12:30", durationMinutes: 60, step: "Buffet lunch on board — Egyptian mezze, grilled fish, fresh fruit and soft drinks" },
        { time: "13:30", durationMinutes: 120, step: "Relaxed afternoon — sunbathing on deck, optional free snorkeling near the boat" },
        { time: "15:30", durationMinutes: 30, step: "Return boat trip to marina" },
        { time: "16:00", durationMinutes: 0, step: "Hotel drop-off" },
      ],
    },
  },
  {
    title: "Snorkeling in Qulaan Islands",
    slug: "snorkeling-qulaan-islands-marsa-alam",
    description:
      "Sail south to the remote and spectacular Qulaan Islands for a full-day snorkeling adventure in one of the most unspoiled marine environments on the entire Red Sea coast, a destination distant enough that most visitors to Marsa Alam never make it this far south. Located within the protected Wadi El Gemal National Park near Hamata, the Qulaan Archipelago is surrounded by pristine coral reefs, crystal-clear waters, and a rich diversity of marine life including reef sharks, dolphins, sea turtles, and hundreds of species of fish, all sheltered within one of Egypt's most carefully protected marine reserves. You'll snorkel at multiple reef points and stop on one of the islands to walk its white sandy beaches and explore its lush flora and fauna, a rare chance to set foot on land that sees only a handful of visitors on any given day.",
    category: "Boat tour",
    price: {
      original: 55.00,
      discounted: null,
      currency: "USD",
    },
    duration: "9 hours",
    language: ["English"],
    rating: {
      score: 8.5,
      reviews: 18,
    },
    travellers: 196,
    freeCancellation: true,
    highlights: [
      "Boat trip to the remote Qulaan Islands",
      "Snorkel at multiple pristine reef points",
      "Explore the island's beaches and wildlife",
      "Spot dolphins, sea turtles, and reef sharks",
      "Buffet lunch on board included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Buffet lunch", "Hotel pickup and drop-off"],
    excludes: ["Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "9 hours",
      startTime: "07:00",
      endTime: "16:00",
      narrative:
        "A full-day southward expedition to the remote Qulaan Archipelago inside Wadi El Gemal National Park. Three snorkeling stops at different reef points are spaced across the day, with an island beach walk and a generous on-board buffet lunch. The remoteness of this destination means an early departure is non-negotiable — every minute counts once the long transit south begins.",
      steps: [
        { time: "07:00", durationMinutes: 15, step: "Hotel pickup — early departure essential due to long transit south" },
        { time: "07:15", durationMinutes: 15, step: "Board boat at marina — safety briefing and snorkeling equipment distribution" },
        { time: "07:30", durationMinutes: 90, step: "Boat transit south to Qulaan Archipelago inside Wadi El Gemal National Park" },
        { time: "09:00", durationMinutes: 60, step: "First snorkeling stop — pristine outer reef wall with sharks, turtles and pelagic fish" },
        { time: "10:00", durationMinutes: 60, step: "Second snorkeling stop — coral garden inside the lagoon with dense reef fish schools" },
        { time: "11:00", durationMinutes: 45, step: "Island stop — walk the white sandy beaches, explore native flora and birdlife" },
        { time: "11:45", durationMinutes: 75, step: "Buffet lunch on board — fresh fruit, Egyptian dishes and cold drinks" },
        { time: "13:00", durationMinutes: 60, step: "Third snorkeling stop — second reef with dolphins frequently spotted in this area" },
        { time: "14:00", durationMinutes: 90, step: "Return boat transit north back to Marsa Alam marina" },
        { time: "15:30", durationMinutes: 30, step: "Arrive marina — gear collection and hotel drop-off" },
      ],
    },
  },
  {
    title: "Red Sea Egyptian Boat Tour",
    slug: "red-sea-egyptian-boat-tour-marsa-alam",
    description:
      "Step aboard the Nefertari — a stunning Egyptian-themed boat decorated like the interior of an ancient pharaonic tomb — for a unique and magical day on the Red Sea, an experience that turns the journey itself into part of the attraction rather than just a means of getting from marina to reef. The boat's lower observation deck sits three meters below the waterline, offering panoramic window views of the coral reef, sea turtles, stingrays, dolphins, and if you're very lucky, the elusive dugong (sea cow) that inhabits these protected waters, all visible without anyone needing to get wet at all. Sail to Marsa Mubarak, one of the most beautiful bays in Egypt, for snorkeling sessions, and enjoy a delicious on-board lunch on this extraordinary floating museum experience, equally suited to confident divers and to family members who would rather stay dry and watch through the glass.",
    category: "Boat tour",
    price: {
      original: 48.00,
      discounted: null,
      currency: "USD",
    },
    duration: "7 hours",
    language: ["English"],
    rating: {
      score: 8.3,
      reviews: 27,
    },
    travellers: 345,
    freeCancellation: true,
    highlights: [
      "Sail aboard the unique Egyptian-themed Nefertari boat",
      "Observe marine life through underwater panoramic windows",
      "Chance to spot dugongs, dolphins, and sea turtles",
      "Snorkeling at Marsa Mubarak bay",
      "On-board lunch included",
    ],
    includes: ["Boat trip", "Underwater observation deck", "Snorkeling equipment", "Lunch", "Hotel pickup and drop-off"],
    excludes: ["Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "7 hours",
      startTime: "09:00",
      endTime: "16:00",
      narrative:
        "A uniquely theatrical day at sea aboard the Nefertari — a pharaonic-themed vessel with an underwater observation deck three meters below the waterline. The experience alternates between passive reef viewing through panoramic windows and active snorkeling at Marsa Mubarak, making it ideal for mixed groups including non-swimmers who still want a genuine front-row seat to the reef.",
      steps: [
        { time: "09:00", durationMinutes: 15, step: "Hotel pickup and transfer to marina" },
        { time: "09:15", durationMinutes: 15, step: "Board the Nefertari boat — welcome orientation and tour of the pharaonic décor" },
        { time: "09:30", durationMinutes: 30, step: "Depart marina and sail towards Marsa Mubarak bay" },
        { time: "10:00", durationMinutes: 60, step: "Underwater observation deck session 1 — panoramic window views of coral reef, turtles, rays, and reef fish as the boat drifts slowly" },
        { time: "11:00", durationMinutes: 90, step: "First snorkeling session at Marsa Mubarak — turtle encounters and coral gardens" },
        { time: "12:30", durationMinutes: 60, step: "On-board lunch — Egyptian dishes served in the decorated dining area" },
        { time: "13:30", durationMinutes: 60, step: "Underwater observation deck session 2 — chance to spot dugongs in deeper water" },
        { time: "14:30", durationMinutes: 60, step: "Second snorkeling session — free exploration near the boat" },
        { time: "15:30", durationMinutes: 30, step: "Return to marina" },
        { time: "16:00", durationMinutes: 0, step: "Hotel drop-off" },
      ],
    },
  },
  {
    title: "Desert Quad Tour + Camel Ride + Dinner & Show",
    slug: "desert-quad-camel-ride-dinner-show-marsa-alam",
    description:
      "Experience the wild and dramatic Eastern Desert of Marsa Alam at its most magical on this unforgettable sunset desert adventure, an experience timed deliberately around the golden hour rather than crammed into the middle of the day. Race across the golden dunes on a powerful quad bike for 40 minutes, weaving through the desert terrain until you reach a traditional Bedouin village where you'll sip sweet Bedouin tea and learn about desert life from people whose families have lived this way for generations. As the sun sets spectacularly over the dunes, hop onto a camel and ride through the cooling desert before gathering around a camp fire for a lively traditional show and a delicious Bedouin dinner under a vast, star-filled sky, the kind of night that tends to outshine even the diving and snorkeling in people's memories of the trip.",
    category: "Day trip",
    price: {
      original: 55.00,
      discounted: null,
      currency: "USD",
    },
    duration: "7 hours",
    language: ["English"],
    rating: {
      score: 7.8,
      reviews: 19,
    },
    travellers: 267,
    freeCancellation: true,
    highlights: [
      "40-minute quad bike ride through desert dunes",
      "Visit a traditional Bedouin village",
      "Camel ride at sunset",
      "Traditional Bedouin dinner under the stars",
      "Live music and dance show",
    ],
    includes: ["Quad bike", "Camel ride", "Bedouin dinner", "Show", "Hotel pickup and drop-off"],
    excludes: ["Alcoholic drinks", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "7 hours",
      startTime: "15:30",
      endTime: "22:30",
      narrative:
        "A sunset-timed desert adventure that makes the most of the cooler late afternoon and evening hours. The tour is deliberately scheduled to reach the dunes at the golden hour, ride the camel as the sun dips, and sit down to dinner under a sky blazing with stars far from any city light pollution.",
      steps: [
        { time: "15:30", durationMinutes: 30, step: "Hotel pickup and drive into the Eastern Desert" },
        { time: "16:00", durationMinutes: 15, step: "Arrival at desert basecamp — safety briefing and quad bike helmet fitting" },
        { time: "16:15", durationMinutes: 40, step: "Quad bike ride — 40 minutes through golden dunes and desert terrain towards the Bedouin village" },
        { time: "16:55", durationMinutes: 45, step: "Arrive Bedouin village — sweet Bedouin tea, cultural exchange and desert life stories from local hosts" },
        { time: "17:40", durationMinutes: 30, step: "Camel ride at sunset — ride through the cooling dunes as the sky turns orange and red" },
        { time: "18:10", durationMinutes: 50, step: "Watch the sun set over the desert — photography time and free exploration of the dunes on foot" },
        { time: "19:00", durationMinutes: 30, step: "Campfire lit — traditional music begins, guests settle around the fire" },
        { time: "19:30", durationMinutes: 60, step: "Live traditional Bedouin music and dance show around the campfire" },
        { time: "20:30", durationMinutes: 90, step: "Bedouin dinner under the stars — grilled meats, rice, salads, flatbread and Bedouin tea" },
        { time: "22:00", durationMinutes: 30, step: "Return drive to hotel drop-off" },
      ],
    },
  },
  {
    title: "Quad Tour + Camel Ride + Snorkeling in the Red Sea",
    slug: "quad-camel-ride-snorkeling-red-sea-marsa-alam",
    description:
      "Combine the best of land and sea in one incredible action-packed day in Marsa Alam on this desert and sea adventure, a single compact outing that somehow manages to fit three completely different Egyptian experiences into one morning. Begin by racing across the Saharan dunes on a quad bike for an hour, covering 25-30 kilometers of dramatic desert terrain before reaching a Bedouin village where you'll share tea with local inhabitants and learn about their ancient desert traditions, traditions that have survived largely unchanged despite the modern resorts now visible from a distance along the coast. Then hop onto a camel for a peaceful 15-minute ride through the sand before jumping on a bus to the coast for a refreshing snorkeling session in the crystal-clear waters of the Red Sea, washing away the desert dust in the very same morning you kicked it up.",
    category: "Adventure and nature",
    price: {
      original: 45.00,
      discounted: null,
      currency: "USD",
    },
    duration: "3 hours",
    language: ["English"],
    rating: {
      score: 7.9,
      reviews: 15,
    },
    travellers: 189,
    freeCancellation: true,
    highlights: [
      "1-hour quad bike ride through Saharan desert",
      "Visit a traditional Bedouin village for tea",
      "15-minute camel ride through the dunes",
      "Snorkeling session in the Red Sea",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Quad bike", "Camel ride", "Snorkeling equipment", "Guide", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "3 hours",
      startTime: "08:00",
      endTime: "11:00",
      narrative:
        "A compact but exhilarating morning that packs three entirely different experiences — desert quad, camel, and Red Sea snorkeling — into just three hours. The early start ensures cool desert air for the quad ride, with the snorkeling session perfectly timed for calm morning sea conditions right at the point when the desert heat starts to build.",
      steps: [
        { time: "08:00", durationMinutes: 15, step: "Hotel pickup and short drive to desert basecamp" },
        { time: "08:15", durationMinutes: 15, step: "Safety briefing and quad bike helmet and gear fitting" },
        { time: "08:30", durationMinutes: 60, step: "Quad bike ride — 1 hour, 25-30 km through Saharan dunes and rocky desert landscape to the Bedouin village" },
        { time: "09:30", durationMinutes: 20, step: "Bedouin village visit — sweet tea and brief cultural exchange with local inhabitants" },
        { time: "09:50", durationMinutes: 15, step: "Camel ride through the dunes back towards the road" },
        { time: "10:05", durationMinutes: 10, step: "Transfer by bus from desert to the Red Sea coast" },
        { time: "10:15", durationMinutes: 30, step: "Snorkeling session in the Red Sea — rinse off the desert dust in crystal-clear water" },
        { time: "10:45", durationMinutes: 15, step: "Return transfer to hotel" },
      ],
    },
  },
  {
    title: "Red Sea Beginners Scuba Diving",
    slug: "red-sea-beginners-scuba-diving-marsa-alam",
    description:
      "Discover the incredible underwater world of Marsa Alam's Red Sea on this beginner-friendly scuba diving experience that requires absolutely no prior experience, designed from the ground up for people who have never so much as worn a mask and fins before. Your certified dive instructor will walk you through all the essential safety techniques and basic diving skills on dry land before accompanying you into the water for dives at two of the best spots along Marsa Alam's stunning coastline, never rushing the process and always staying within arm's reach as you build confidence. With its pristine coral reefs, extraordinary visibility, and a remarkable variety of marine life, the Red Sea at Marsa Alam is one of the most rewarding places on Earth for a first dive, the kind of underwater debut that has a habit of permanently changing how people think about the ocean.",
    category: "Adventure and nature",
    price: {
      original: 65.00,
      discounted: null,
      currency: "USD",
    },
    duration: "6 hours",
    language: ["English"],
    rating: {
      score: 8.6,
      reviews: 22,
    },
    travellers: 198,
    freeCancellation: true,
    highlights: [
      "Two beginner scuba dives in Marsa Alam's Red Sea",
      "Certified dive instructor throughout",
      "No prior experience required",
      "World-class coral reefs and marine life",
      "All diving equipment provided",
    ],
    includes: ["Two dives", "All diving equipment", "Certified instructor", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "6 hours",
      startTime: "08:00",
      endTime: "14:00",
      narrative:
        "A carefully structured six-hour introduction to scuba diving that never rushes a beginner. One full hour on dry land is dedicated to safety and technique before any water entry. Two dives at separate reef sites build confidence progressively, with a full surface interval between them. The 18-hour no-fly rule makes this best planned for non-departure days.",
      steps: [
        { time: "08:00", durationMinutes: 15, step: "Hotel pickup and transfer to dive centre" },
        { time: "08:15", durationMinutes: 60, step: "Dry land training — diving signals, mask clearing, regulator breathing, buoyancy basics and emergency procedures with certified instructor" },
        { time: "09:15", durationMinutes: 15, step: "Equipment fitting — wetsuit, BCD, tank, fins and mask" },
        { time: "09:30", durationMinutes: 60, step: "First scuba dive at Marsa Alam reef site 1 — shallow dive (5-8m) with instructor, focus on coral life and technique" },
        { time: "10:30", durationMinutes: 45, step: "Surface interval — rest on the boat, refreshments, instructor debrief and tips for the second dive" },
        { time: "11:15", durationMinutes: 60, step: "Second scuba dive at reef site 2 — slightly deeper (8-12m), explore coral wall, moray eels, lionfish and reef sharks" },
        { time: "12:15", durationMinutes: 30, step: "Return to dive centre — equipment rinse and return" },
        { time: "12:45", durationMinutes: 15, step: "Receive dive log entry and certificate of first dive from instructor" },
        { time: "13:00", durationMinutes: 60, step: "Optional: lunch near the dive centre before hotel drop-off" },
        { time: "14:00", durationMinutes: 0, step: "Hotel drop-off" },
      ],
    },
  },
  {
    title: "Civitatis eSIM Card Egypt",
    slug: "civitatis-esim-card-egypt-marsa-alam",
    description:
      "Stay connected throughout your Marsa Alam adventure with this practical travel eSIM, one less thing to arrange once your flight touches down. Whether you're sharing photos from Sataya Dolphin House, navigating to remote dive sites scattered well outside town, or looking up information about the Red Sea marine life you've just spotted, this eSIM gives you reliable mobile data coverage across Egypt without the hassle of finding a local SIM card in a town with relatively few shops to begin with. Simply activate digitally before you travel and enjoy seamless connectivity from the moment you land, lasting through every dive, desert excursion, and quiet beach afternoon on your itinerary.",
    category: "Additional services",
    price: {
      original: 5.50,
      discounted: null,
      currency: "USD",
    },
    duration: "7-30 days",
    language: ["English"],
    rating: {
      score: 7.7,
      reviews: 107,
    },
    travellers: 2096,
    freeCancellation: false,
    highlights: [
      "Mobile data coverage across Egypt",
      "No physical SIM swap needed",
      "Easy digital activation before arrival",
      "Available in 7, 15, and 30-day plans",
      "Works in Marsa Alam and all Egyptian destinations",
    ],
    includes: ["eSIM data plan for selected duration"],
    excludes: ["Voice calls", "SMS"],
    tourSchedule: null,
  },
  {
    title: "Red Sea Semi-Submarine Tour",
    slug: "red-sea-semi-submarine-tour-marsa-alam",
    description:
      "Explore the magical underwater world of the Red Sea without getting wet on this fascinating semi-submarine tour from Marsa Alam, an option built specifically for travelers who want the reef experience but not necessarily the snorkel mask. Board the specially designed vessel and descend to the lower observation deck, where large panoramic windows give you unobstructed views of the spectacular coral reefs, tropical fish, rays, and sea turtles gliding through the crystal-clear water beneath you, the whole scene unfolding slowly and clearly as the boat drifts. The semi-submarine sails along the most beautiful and biodiverse stretch of Marsa Alam's coast, offering a unique and accessible way for all ages to experience the Red Sea's extraordinary marine treasures, particularly well suited to grandparents, young children, or anyone simply not keen on swimming that day.",
    category: "Boat tour",
    price: {
      original: 38.00,
      discounted: null,
      currency: "USD",
    },
    duration: "3 hours",
    language: ["English"],
    rating: {
      score: 7.9,
      reviews: 14,
    },
    travellers: 163,
    freeCancellation: true,
    highlights: [
      "Semi-submarine ride along Marsa Alam's coast",
      "Panoramic underwater views without diving",
      "See coral reefs, fish, rays, and sea turtles",
      "Suitable for all ages including non-swimmers",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Semi-submarine ride", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "3 hours",
      startTime: "10:00",
      endTime: "13:00",
      narrative:
        "A relaxed three-hour coastal cruise aboard a semi-submarine, ideal for families, elderly guests, or anyone who wants the Red Sea experience without getting wet. The observation deck three meters below the waterline turns the sea floor into a living aquarium, with nothing required of passengers beyond simply looking out the window.",
      steps: [
        { time: "10:00", durationMinutes: 15, step: "Hotel pickup and transfer to marina" },
        { time: "10:15", durationMinutes: 15, step: "Board the semi-submarine — guide explains the vessel and the reef ecosystem" },
        { time: "10:30", durationMinutes: 30, step: "Descend to underwater observation deck — panoramic window views as the vessel moves slowly along the reef" },
        { time: "11:00", durationMinutes: 30, step: "Observation deck session 2 — deeper reef section with schools of tropical fish and rays" },
        { time: "11:30", durationMinutes: 30, step: "Return to upper deck — guide commentary on marine life spotted, refreshments served" },
        { time: "12:00", durationMinutes: 30, step: "Final observation deck pass — turtle spotting zone near the seagrass meadows" },
        { time: "12:30", durationMinutes: 30, step: "Return to marina and hotel drop-off" },
      ],
    },
  },
  {
    title: "Day Trip to Luxor from Marsa Alam",
    slug: "day-trip-luxor-marsa-alam",
    description:
      "Venture inland from the Red Sea coast on this extraordinary day trip to Luxor, one of the greatest ancient cities in the world, trading the turquoise water for the desert gold of ancient Thebes for a single, unforgettable day. The journey by minibus takes approximately five hours each way, but the remarkable experiences that await make every minute worthwhile, your guide using the long drive to lay out the history and context you'll need once you arrive. Your expert Egyptologist guide will take you to the Valley of the Kings to explore three elaborately decorated royal tombs, the stunning cliff-carved Mortuary Temple of Hatshepsut, and the towering Colossi of Memnon, four very different monuments that together sketch out the scale and ambition of New Kingdom Egypt. For those with energy to spare, an optional afternoon boat trip on the Nile can be arranged, a quiet final note before the long drive back across the desert to the coast.",
    category: "Day trip",
    price: {
      original: 95.00,
      discounted: null,
      currency: "USD",
    },
    duration: "11 hours",
    language: ["English"],
    rating: {
      score: 8.4,
      reviews: 67,
    },
    travellers: 712,
    freeCancellation: true,
    highlights: [
      "Visit the Valley of the Kings and three royal tombs",
      "See the Mortuary Temple of Hatshepsut",
      "Admire the Colossi of Memnon",
      "Expert Egyptologist guide throughout",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Guide", "Hotel pickup and drop-off", "Transport", "Entrance fees", "Lunch"],
    excludes: ["Tutankhamun tomb (extra fee)", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "11 hours",
      startTime: "05:00",
      endTime: "16:00",
      narrative:
        "A long but deeply rewarding day that crosses the Eastern Desert to reach Luxor — the world's greatest open-air museum. The 5 AM departure is non-negotiable: it places you at the Valley of the Kings before the tour-bus crowds arrive and before the temperature makes the outdoor sites uncomfortable. Every hour of sleep lost on the drive is repaid a hundredfold by what you find on the West Bank.",
      steps: [
        { time: "05:00", durationMinutes: 15, step: "Hotel pickup — very early departure to beat the desert heat and tourist crowds in Luxor" },
        { time: "05:15", durationMinutes: 295, step: "Minibus journey west across the Eastern Desert to Luxor — approximately 5 hours, guide shares Egyptological context en route" },
        { time: "10:10", durationMinutes: 20, step: "Arrive Luxor West Bank — brief orientation stop at the Colossi of Memnon" },
        { time: "10:30", durationMinutes: 90, step: "Valley of the Kings — enter three elaborately decorated royal tombs with Egyptologist guide (tomb selection based on current access)" },
        { time: "12:00", durationMinutes: 45, step: "Mortuary Temple of Hatshepsut — the spectacular cliff-carved temple of Egypt's greatest female pharaoh" },
        { time: "12:45", durationMinutes: 60, step: "Lunch at a local Luxor restaurant — Egyptian cuisine in the heart of ancient Thebes" },
        { time: "13:45", durationMinutes: 30, step: "Optional: Nile felucca boat ride (extra fee) OR free time in the temple area" },
        { time: "14:15", durationMinutes: 5, step: "Final stop — Colossi of Memnon for photos" },
        { time: "14:20", durationMinutes: 280, step: "Return minibus journey east across the desert back to Marsa Alam" },
        { time: "19:00", durationMinutes: 0, step: "Arrive Marsa Alam — hotel drop-off" },
      ],
    },
  },
  {
    title: "Civitatis Travel Insurance",
    slug: "civitatis-travel-insurance-marsa-alam",
    description:
      "Explore Marsa Alam's wild reefs and desert landscapes with complete peace of mind thanks to Civitatis Travel Insurance, a quiet layer of protection running underneath every dive, snorkel, and desert excursion on your itinerary. Whether you're diving at Elphinstone Reef, snorkeling with dolphins at Sataya, or trekking through the Eastern Desert, this comprehensive travel insurance covers medical emergencies, trip cancellations, lost luggage, and much more, the kind of coverage that matters most precisely in a destination this far from major hospitals and city infrastructure. Available for trips lasting between 3 and 31 days, it's the smart traveler's essential companion for any Egyptian adventure, whether spent mostly underwater or mostly in the dunes.",
    category: "Additional services",
    price: {
      original: 11.48,
      discounted: null,
      currency: "USD",
    },
    duration: "3-31 days",
    language: ["English"],
    rating: {
      score: 8.2,
      reviews: 3059,
    },
    travellers: 105388,
    freeCancellation: false,
    highlights: [
      "Comprehensive travel insurance for Marsa Alam and Egypt",
      "Covers medical emergencies and trip cancellations",
      "Available for 3 to 31-day trips",
      "Peace of mind for diving, snorkeling, and desert activities",
    ],
    includes: ["Travel insurance coverage as per selected plan"],
    excludes: ["Pre-existing medical conditions (check policy)"],
    tourSchedule: null,
  },
  {
    title: "Sataya Reef Boat Trip + Snorkeling with Dolphins",
    slug: "sataya-reef-boat-trip-snorkeling-dolphins-marsa-alam",
    description:
      "Embark on one of the most extraordinary wildlife encounters available anywhere in Egypt on this full-day boat trip to Sataya Reef, also known as Dolphin House — a legendary Red Sea marine reserve that is home to a permanent resident pod of Red Sea spinner dolphins, animals that have made this lagoon their home for generations rather than simply passing through. Sail south from Marsa Alam to reach this remote and pristine reef, then slip into the warm turquoise water for a two-hour snorkeling session alongside these incredible and playful animals as they spin, leap, and glide through the water around you in their natural habitat, utterly unbothered by your presence as long as you keep your distance and let them set the pace. A truly life-changing experience, and consistently the single most talked-about moment of any Marsa Alam holiday.",
    category: "Boat tour",
    price: {
      original: 75.00,
      discounted: null,
      currency: "USD",
    },
    duration: "9 hours",
    language: ["English"],
    rating: {
      score: 9.1,
      reviews: 38,
    },
    travellers: 487,
    freeCancellation: true,
    highlights: [
      "Boat trip to the legendary Sataya Dolphin House reef",
      "2-hour snorkeling session with wild spinner dolphins",
      "Explore hidden caves and tunnels around the reef",
      "Buffet lunch with fresh fruit and drinks included",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Boat trip", "Snorkeling equipment", "Buffet lunch and drinks", "Guide", "Hotel pickup and drop-off"],
    excludes: ["Airport pickup (extra fee)", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "9 hours",
      startTime: "06:30",
      endTime: "15:30",
      narrative:
        "The flagship experience of Marsa Alam and one of the most extraordinary wildlife encounters in all of Egypt. The early departure is critical — spinner dolphins are most active and curious in the morning hours. Two separate snorkeling sessions are scheduled: the first for dolphin interaction in open water, the second for exploring the reef's caves and tunnel formations.",
      steps: [
        { time: "06:30", durationMinutes: 15, step: "Hotel pickup — very early departure for the long southbound journey to Sataya" },
        { time: "06:45", durationMinutes: 15, step: "Board boat at marina — safety briefing and dolphin etiquette guidelines from guide" },
        { time: "07:00", durationMinutes: 150, step: "Boat journey south approximately 2.5 hours to Sataya Reef (Dolphin House)" },
        { time: "09:30", durationMinutes: 15, step: "Arrive Sataya — observe the dolphin pod from the boat before entering the water" },
        { time: "09:45", durationMinutes: 120, step: "First snorkeling session — 2 hours in the water with wild resident spinner dolphins in their natural lagoon habitat" },
        { time: "11:45", durationMinutes: 45, step: "Back on boat — rest, refreshments, guide narrates facts about spinner dolphins and Sataya Reef ecology" },
        { time: "12:30", durationMinutes: 60, step: "Buffet lunch on board — fresh fruit, Egyptian dishes, grilled fish and soft drinks" },
        { time: "13:30", durationMinutes: 60, step: "Second snorkeling session — explore the reef's hidden caves, underwater tunnels and the outer wall with diverse coral life" },
        { time: "14:30", durationMinutes: 60, step: "Return boat journey north to Marsa Alam marina" },
        { time: "15:30", durationMinutes: 0, step: "Arrive marina — hotel drop-off" },
      ],
    },
  },
  {
    title: "Desert Camel Ride in Marsa Alam",
    slug: "desert-camel-ride-marsa-alam",
    description:
      "Experience one of the most iconic and timeless ways to explore the Egyptian desert on this relaxed camel ride through the dunes surrounding Marsa Alam, a mode of transport that connected this stretch of coast to the rest of Egypt long before any paved road existed. Suitable for adults and children alike, this gentle one-hour adventure takes you away from the coast and into the vast, sun-baked expanse of the Eastern Desert, riding these extraordinary desert animals through golden sand dunes and among scattered acacia trees that somehow manage to survive on almost no water at all. Your instructor will show you how to mount and guide your camel, and will share fascinating facts about the role these animals have played throughout Egypt's long history, from ancient trade caravans to the modern tourism that now provides their livelihood.",
    category: "Adventure and nature",
    price: {
      original: 22.00,
      discounted: null,
      currency: "USD",
    },
    duration: "2 hours",
    language: ["English"],
    rating: {
      score: 7.5,
      reviews: 11,
    },
    travellers: 145,
    freeCancellation: true,
    highlights: [
      "One-hour camel ride through desert dunes",
      "Suitable for adults and children",
      "Scenic Eastern Desert landscape",
      "Learn about camels' role in Egyptian history",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Camel ride", "Instructor", "Tea/coffee", "Hotel pickup and drop-off"],
    excludes: ["Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "2 hours",
      startTime: "07:00",
      endTime: "09:00",
      narrative:
        "A short and sweet early-morning desert experience — perfect as an add-on to a beach day or as a gentle introduction to the Eastern Desert for families and first-time Egypt visitors. The early hour keeps it cool and the light is spectacular for photography, the low morning sun raking across the dunes in long golden streaks.",
      steps: [
        { time: "07:00", durationMinutes: 15, step: "Hotel pickup and short drive to camel stable at desert edge" },
        { time: "07:15", durationMinutes: 15, step: "Instructor introduction — meet your camel, learn mounting technique and basic camel guidance commands" },
        { time: "07:30", durationMinutes: 60, step: "One-hour camel ride through Eastern Desert dunes and acacia tree landscape — instructor shares camel history and Bedouin desert lore" },
        { time: "08:30", durationMinutes: 15, step: "Return to stables — dismount and farewell tea or coffee with the camel handlers" },
        { time: "08:45", durationMinutes: 15, step: "Return drive to hotel" },
      ],
    },
  },
  {
    title: "Desert Quad Tour in Marsa Alam",
    slug: "desert-quad-tour-marsa-alam",
    description:
      "Tear through the dramatic Eastern Desert surrounding Marsa Alam on an exhilarating quad bike safari, a tour built for travelers who want raw speed and dust rather than the slower pace of a camel. Navigate golden sand dunes, rocky desert tracks, and open desert plains as the rugged landscape of southern Egypt's interior stretches out endlessly before you, the coastline and its hotels disappearing from view within minutes of leaving the basecamp. The tour includes a stop at a traditional Bedouin village where you'll be welcomed with sweet desert tea and given an insight into the remarkable lives of the nomadic people who have called this harsh but beautiful landscape home for generations, their hospitality unchanged despite the steady stream of visitors passing through on quad bikes their grandparents could never have imagined. A thrilling and authentic desert adventure.",
    category: "Adventure and nature",
    price: {
      original: 35.00,
      discounted: null,
      currency: "USD",
    },
    duration: "3 hours",
    language: ["English"],
    rating: {
      score: 7.6,
      reviews: 9,
    },
    travellers: 124,
    freeCancellation: true,
    highlights: [
      "Quad bike ride through Eastern Desert dunes",
      "Visit a traditional Bedouin village",
      "Enjoy sweet Bedouin tea with local hosts",
      "Dramatic desert scenery of southern Egypt",
      "Hotel pickup and drop-off included",
    ],
    includes: ["Quad bike", "Safety equipment", "Guide", "Bedouin tea", "Hotel pickup and drop-off"],
    excludes: ["Meals", "Tips", "Personal expenses"],
    tourSchedule: {
      totalDuration: "3 hours",
      startTime: "08:00",
      endTime: "11:00",
      narrative:
        "A focused three-hour quad safari through the Eastern Desert, structured around two riding legs with a cultural pause at a Bedouin village in between. The morning departure exploits the cooler temperatures and golden desert light before the heat becomes intense.",
      steps: [
        { time: "08:00", durationMinutes: 15, step: "Hotel pickup and drive to desert basecamp" },
        { time: "08:15", durationMinutes: 15, step: "Safety briefing — helmet fitting, throttle and brake controls, emergency stop procedure" },
        { time: "08:30", durationMinutes: 45, step: "First riding leg — quad bike through open desert dunes and rocky plateau towards the Bedouin village" },
        { time: "09:15", durationMinutes: 30, step: "Bedouin village stop — sweet desert tea with local hosts, learn about nomadic desert life and Bedouin traditions" },
        { time: "09:45", durationMinutes: 45, step: "Second riding leg — loop back through a different desert track with sand dunes and rocky desert plains" },
        { time: "10:30", durationMinutes: 15, step: "Return to basecamp — helmet and gear return" },
        { time: "10:45", durationMinutes: 15, step: "Return drive to hotel drop-off" },
      ],
    },
  },
];

export { cityData, cityItinerary, toursData };